__title__ = 'Flask-Language'
__version__ = '0.1.0'
__description__ = 'Flask extension handling client-side language cookie'
__author__ = 'Romain Clement'
__author_email__ = 'r.clement88@gmail.com'
__url__ = 'https://github.com/rclement/flask-language'
__license__ = 'MIT'
